### ISSUE TITLE
It keeps complaining about this but I've installed all the packages

### ISSUE THREAD

**Issue by Benighter** [lee88688/aider-composer#48]
2024-12-12 04:55:27.890 [info] Restarting aider-chat service...
2024-12-12 04:55:27.890 [info] Stopping aider-chat service...
2024-12-12 04:55:27.890 [info] Starting aider-chat service...
2024-12-12 04:55:27.897 [info] aider-chat process args: C:\Users\mphoc\AppData\Local\Programs\Python\Python311\python.exe -m flask -A c:\Users\mphoc\.vscode\extensions\lee2py.aider-composer-1.6.0\server\main.py run --port 19180
2024-12-12 04:55:28.542 [info] aider-chat: Usage: python -m flask run [OPTIONS]
2024-12-12 04:55:28.542 [info] aider-chat: Try 'python -m flask run --help' for help.
2024-12-12 04:55:28.542 [info] aider-chat: 
2024-12-12 04:55:28.542 [info] aider-chat: Error: While importing 'main', an ImportError was raised:
2024-12-12 04:55:28.542 [info] aider-chat: 
2024-12-12 04:55:28.542 [info] aider-chat: Traceback (most recent call last):
2024-12-12 04:55:28.542 [info] aider-chat:   File "C:\Users\mphoc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\cli.py", line 245, in locate_app
2024-12-12 04:55:28.542 [info] aider-chat:     __import__(module_name)
2024-12-12 04:55:28.542 [info] aider-chat:   File "C:\Users\mphoc\.vscode\extensions\lee2py.aider-composer-1.6.0\server\main.py", line 4, in <module>
2024-12-12 04:55:28.542 [info] aider-chat:     from aider.coders import Coder
2024-12-12 04:55:28.542 [info] aider-chat:   File "C:\Users\mphoc\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\coders\__init__.py", line 1, in <module>
2024-12-12 04:55:28.543 [info] aider-chat:     from .architect_coder import ArchitectCoder
2024-12-12 04:55:28.543 [info] aider-chat:   File "C:\Users\mphoc\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\coders\architect_coder.py", line 2, in <module>
2024-12-12 04:55:28.543 [info] aider-chat:     from .ask_coder import AskCoder
2024-12-12 04:55:28.543 [info] aider-chat:   File "C:\Users\mphoc\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\coders\ask_coder.py", line 2, in <module>
2024-12-12 04:55:28.543 [info] aider-chat:     from .base_coder import Coder
2024-12-12 04:55:28.543 [info] aider-chat:   File "C:\Users\mphoc\AppData\Local\Programs\Python\Python311\Lib\site-packages\aider\coders\base_coder.py", line 22, in <module>
2024-12-12 04:55:28.543 [info] aider-chat:     from aider import __version__, models, prompts, urls, utils
2024-12-12 04:55:28.543 [info] aider-chat: ImportError: cannot import name '__version__' from 'aider' (unknown location)
2024-12-12 04:55:28.543 [info] aider-chat: 
2024-12-12 04:55:28.613 [error] aider-chat service exited with code 2 and signal null
2024-12-12 04:55:28.613 [error] aider-chat service closed

**Comment by lee88688** [comment]
what flask version did you install?
