### ISSUE TITLE
fancy_input argument error

### ISSUE THREAD

**Issue by callbacked** [lee88688/aider-composer#6]
Hello, I was setting this up and looking at the logs it seems that it does not like the fancy_input argument

```python
2024-11-13 22:34:05.823 [info] Extension "aider-composer" is now active!
2024-11-13 22:34:05.823 [info] Starting aider-chat service...
2024-11-13 22:34:05.823 [info] aider-chat process args: /Users/alex/.pyenv/shims/python -m flask -A /Users/alex/.vscode/extensions/lee2py.aider-composer-1.1.1/server/main.py run --port 12209
2024-11-13 22:34:07.231 [info] aider-chat: Traceback (most recent call last):
2024-11-13 22:34:07.231 [info] aider-chat:   File "<frozen runpy>", line 198, in _run_module_as_main
2024-11-13 22:34:07.231 [info] aider-chat:   File "<frozen runpy>", line 88, in _run_code
2024-11-13 22:34:07.231 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/__main__.py", line 3, in <module>
2024-11-13 22:34:07.231 [info] aider-chat:     main()
2024-11-13 22:34:07.231 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/cli.py", line 1105, in main
2024-11-13 22:34:07.232 [info] aider-chat:     cli.main()
2024-11-13 22:34:07.232 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1078, in main
2024-11-13 22:34:07.232 [info] aider-chat:     rv = self.invoke(ctx)
2024-11-13 22:34:07.232 [info] aider-chat:          ^^^^^^^^^^^^^^^^
2024-11-13 22:34:07.232 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
2024-11-13 22:34:07.232 [info] aider-chat:     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-11-13 22:34:07.232 [info] aider-chat:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-13 22:34:07.232 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2024-11-13 22:34:07.232 [info] aider-chat:     return ctx.invoke(self.callback, **ctx.params)
2024-11-13 22:34:07.232 [info] aider-chat:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-13 22:34:07.232 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2024-11-13 22:34:07.233 [info] aider-chat:     return __callback(*args, **kwargs)
2024-11-13 22:34:07.233 [info] aider-chat:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-13 22:34:07.233 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
2024-11-13 22:34:07.233 [info] aider-chat:     return ctx.invoke(f, obj, *args, **kwargs)
2024-11-13 22:34:07.233 [info] aider-chat:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-13 22:34:07.233 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2024-11-13 22:34:07.233 [info] aider-chat:     return __callback(*args, **kwargs)
2024-11-13 22:34:07.233 [info] aider-chat:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-13 22:34:07.233 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/cli.py", line 953, in run_command
2024-11-13 22:34:07.233 [info] aider-chat:     raise e from None
2024-11-13 22:34:07.233 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/cli.py", line 937, in run_command
2024-11-13 22:34:07.233 [info] aider-chat:     app: WSGIApplication = info.load_app()
2024-11-13 22:34:07.233 [info] aider-chat:                            ^^^^^^^^^^^^^^^
2024-11-13 22:34:07.233 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/cli.py", line 335, in load_app
2024-11-13 22:34:07.233 [info] aider-chat:     app = locate_app(import_name, name)
2024-11-13 22:34:07.233 [info] aider-chat:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-13 22:34:07.233 [info] aider-chat:   File "/Users/alex/.pyenv/versions/3.11.8/lib/python3.11/site-packages/flask/cli.py", line 245, in locate_app
2024-11-13 22:34:07.233 [info] aider-chat:     __import__(module_name)
2024-11-13 22:34:07.233 [info] aider-chat:   File "/Users/alex/.vscode/extensions/lee2py.aider-composer-1.1.1/server/main.py", line 195, in <module>
2024-11-13 22:34:07.233 [info] aider-chat:     manager = ChatSessionManager()
2024-11-13 22:34:07.233 [info] aider-chat:               ^^^^^^^^^^^^^^^^^^^^
2024-11-13 22:34:07.233 [info] aider-chat:   File "/Users/alex/.vscode/extensions/lee2py.aider-composer-1.1.1/server/main.py", line 114, in __init__
2024-11-13 22:34:07.233 [info] aider-chat:     io = CaptureIO(
2024-11-13 22:34:07.233 [info] aider-chat:          ^^^^^^^^^^
2024-11-13 22:34:07.233 [info] aider-chat:   File "/Users/alex/.vscode/extensions/lee2py.aider-composer-1.1.1/server/main.py", line 43, in __init__
2024-11-13 22:34:07.233 [info] aider-chat:     super().__init__(*args, **kwargs)
2024-11-13 22:34:07.233 [info] aider-chat: TypeError: InputOutput.__init__() got an unexpected keyword argument 'fancy_input'
2024-11-13 22:34:07.356 [error] aider-chat service exited with code 1 and signal null
2024-11-13 22:34:07.356 [error] aider-chat service closed
```

My temporary fix was to remove that argument before initializing, which works for now -- but this will probably need more investigation. I don't know why this may be the case.

```python
def __init__(self, *args, **kwargs):
    # pop arg for now
    kwargs.pop('fancy_input', None)
    
    self.lines = []
    self.error_lines = []
    self.write_files = {}
    super().__init__(*args, **kwargs)
 ```
 
 Also side note, I was using this with an OpenAI Compatible API with a custom URL and it had issues where it would not properly handle the ``base_url`` for ``openai_compatible`` providers. I had to modify to have explicit checking for the two cases:  1.) you only need an api key or 2.) you need an api key + custom url. This handles it better. I can open up a PR for this for you to review.
 
 ```python
 def update_model(self, setting: ChatSetting):
    if self.setting != setting:
        self.setting = setting
        model = Model(setting.model)
        # update os env
        config = provider_env_map[setting.provider]
        
        # handle configs that only need an api key
        # ex: 'anthropic': 'ANTHROPIC_API_KEY'
        if isinstance(config, str):
            os.environ[config] = setting.api_key
            
        # handle configs that need multiple env vars, like base urls and api keys
        # ex: openai_compatible: {'api_key': 'OPENAI_API_KEY', 'base_url': 'OPENAI_API_BASE'}
        elif isinstance(config, dict):
            for key, env_var_name in config.items():
                if key == 'api_key':
                    # set the api key env variable
                    # ex: os.environ['OPENAI_API_KEY'] = 'sk-123...'
                    os.environ[env_var_name] = setting.api_key
                elif key == 'base_url':
                    # set the base URL environment variable --> default to empty string if None
                    # ex: os.environ['OPENAI_API_BASE'] = 'https://api.custom-domain.com/v1'
                    os.environ[env_var_name] = setting.base_url or ''
        self.coder = Coder.create(from_coder=self.coder, main_model=model)
  ```

**Comment by lee88688** [comment]
what do the aider-chat version you use? `fancy_input` 's error is caused by latest some version, you can update aider-chat version to fix this error.

**Comment by callbacked** [comment]
@lee88688 Hello, turns out my aider was not updated at all (I thought it was), I will close this issue right away. My apologies.
